### ISSUE TITLE
PitchTracker.dll x64 from Nightly does not work for everyone

### ISSUE THREAD

**Issue by lukeIam** [Vocaluxe/Vocaluxe#173]
For me it works, for others not:
```
System.DllNotFoundException: Die DLL "PitchTracker.dll": Das angegebene Modul wurde nicht gefunden. (Ausnahme von HRESULT: 0x8007007E) kann nicht geladen werden.
bei Vocaluxe.Lib.Sound.Record.PitchTracker.CPtAKF.PtAKF_Create(UInt32 step)
bei Vocaluxe.Lib.Sound.Record.CBuffer..ctor()
bei Vocaluxe.Lib.Sound.Record.CRecordBase.Init()
bei Vocaluxe.Lib.Sound.Record.PortAudio.CPortAudioRecord.Init()
bei Vocaluxe.CMainProgram._Run(String[] args)
```

### Quickfix:
Download this [PitchTracker.dll](https://gist.github.com/lukeIam/caa48176a277444859f5/raw/2289106883d4fd17a589f93c2eaa90abee4c7288/PitchTracker.dll) and replace the existing one

**Comment by lukeIam** [comment]
Please test: https://ci.appveyor.com/api/buildjobs/a2g084fsdker5mo6/artifacts/Vocaluxe_PTFix_Windows_x64.zip

**Comment by Domani89** [comment]
Meybe I have a solution for the problem. There are 2 PitchTracker.dll at the directories.

/libs -> 1 result
/libs/x64 -> 1 result

It looks like, that Vocaluxe use the first one and not the seconde one in the x64 Folder. So maybe the data at the first DLL doesn't work correctly on x64 Systems. In my cases it's a "fresh" windows 10 (newest upgrade from the weekend) and all installation that will be needed. I installed:

"directx_Jun2010_redist"
"gstreamer-1.0-x86_64-1.6.1"
"vcredist_x64"
"SlimDX Runtime .NET 4.0 x64 (January 2012)" - installed because Vocaluxe show error that SlimDX doesn't found

Your solution doesn't work. PitchTracker.dll wasn't found from Vocaluxe. So it need the data at the libs directory?

Maybe it is possible to integrate some setup files in a software directory that needed for vocaluxe.

**Comment by lukeIam** [comment]
@Domani89: have you tried that version?

> Please test: https://ci.appveyor.com/api/buildjobs/a2g084fsdker5mo6/artifacts/Vocaluxe_PTFix_Windows_x64.zip

**Comment by Domani89** [comment]
Error-Log Vocaluxe "Shining Heaven" v0.3.0 (x64) Beta (0.3.0.83-576-g52727a5) 19.12.2015 11:36:15
----------------------------------------

1) Error on start up: System.DllNotFoundException: Die DLL "PitchTracker.dll": Das angegebene Modul wurde nicht gefunden. (Ausnahme von HRESULT: 0x8007007E) kann nicht geladen werden.
   bei Vocaluxe.Lib.Sound.Record.PitchTracker.CPtAKF.PtAKF_Create(UInt32 step)
   bei Vocaluxe.Lib.Sound.Record.CBuffer..ctor()
   bei Vocaluxe.Lib.Sound.Record.CRecordBase.Init()
   bei Vocaluxe.Lib.Sound.Record.PortAudio.CPortAudioRecord.Init()
   bei Vocaluxe.CMainProgram._Run(String[] args)

Yes sure. One minute ago

**Comment by lukeIam** [comment]
@Domani89: Thanks -> I'll will have a look on it again...

> "gstreamer-1.0-x86_64-1.6.1"

Should be included now (if its installed locally, your local version will be used otherwise)

> "SlimDX Runtime .NET 4.0 x64 (January 2012)"

Should also use the one from the zip...



Strange...

**Comment by lukeIam** [comment]
> > "gstreamer-1.0-x86_64-1.6.1"

If the gstreamer environment variable was set with a invalid path Vocaluxe didn't do a fall back to the local gstreamer lib.
This should be fixed with: https://github.com/Vocaluxe/Vocaluxe/commit/f860afdbd4d5b828125798f958fe731cb32b49d1

But according to @Domani89 the original problem (PitchTracker.dll not found) still exists...

**Comment by lukeIam** [comment]
Please test again with:
https://ci.appveyor.com/api/buildjobs/6wix4x8darmwfwrp/artifacts/Vocaluxe_PTFix_Windows_x64.zip
(https://github.com/Vocaluxe/Vocaluxe/commit/67f37b440bdc89a872932a92f1920ea3947e391c)

**Comment by Domani89** [comment]
Works on my laptop

**Comment by lukeIam** [comment]
@Domani89: Thanks for your update!
