### ISSUE TITLE
Sometimes Null-Ref exception while loading background music

### ISSUE THREAD

**Issue by lukeIam** [Vocaluxe/Vocaluxe#330]
"Object reference not set to an instance of an object"

![image](https://user-images.githubusercontent.com/5115160/32405971-c428e518-c16f-11e7-8d75-4f2fd1fcd15b.png)

From: http://forum.ultra-star.de/viewtopic.php?f=90&t=11340#p69707

**Comment by Pr3di** [comment]
In my Branch https://github.com/Pr3di/Vocaluxe/commits/Pr3di i had this Error a well. So i debugged it and found that in Class Vocaluxe\Base\CBackgroundMusic.cs line 340 the instance of _PreviewStartHelperTask is null. 
I dont know why the Programm executes that code at that time because the if-Statemant in line 318 should be true but to fix it I added another condition so check if the instance is null.
