### ISSUE TITLE
Problem duet mode : Colors of the lyrics

### ISSUE THREAD

**Issue by akeix** [Vocaluxe/Vocaluxe#361]
Hello,

In the duo mode for the nightly version, the colors of the lyrics are not those of the players.

The words of the blue player appear in red instead of blue.
The words of the red player appear in blue instead of red.

**Comment by Stefan1200-de** [comment]
Still exists in current nightly:
![image](https://user-images.githubusercontent.com/15168351/72476646-068efe00-37ee-11ea-93e2-7415aa7564ec.png)

**Comment by Stefan1200-de** [comment]
That bug is a nut. At CScreenSing.cs I checked already the _DrawLyricHelper() function, behind _Statics[_StaticLyricHelperDuet].Color.R/G/B are the right values for the red color. Also everything good for _Statics[_StaticLyricHelper].Color.R/G/B, the right values for the blue color. And it seems that the right color will be used, while player 1 and 2 are singing a duet. Totally strange.

**Comment by Stefan1200-de** [comment]
Fixed it, pull requests is online.
![image](https://user-images.githubusercontent.com/15168351/72646485-92339680-3976-11ea-9dc6-7e0133bc41fb.png)

**Comment by Jiiniasu** [comment]
I know this i already closed, but just wanted to give my two cents on this.

The problem with the duet colours is that there are no "correct" colours since the game doesn't actually care who is voice 1 and voice 2 for the lyrics. The specific issue with two players has only been inverted. If P1 chooses to be voice 2 and P2 chooses to be voice 1 the colours will be wrong.

However, this change/fix does align the colours to match the auto voice assignment, as long as you don't have more than two players. A slight improvement at least.
