### ISSUE TITLE
Add Rap Notes (basic support)

### ISSUE THREAD

**Issue by JanK118** [Vocaluxe/Vocaluxe#479]
Vocaluxe doesn't support Rap Notes at all, which USDX does since it's last release in 2017. Even worse, if a song contains a rap note, Vocaluxe ignores the whole song.
From my understanding, rap notes are skipping the note detection, helping to concentrate on the "Flow", which is great. Freestyle notes are not a real option, since there are songs with a lot of rap parts, and you want to have some nice highscores in these too...

I'll share two links with you, in case you want to take a look at it.
https://area91.garycxjk.com/usdx/rap
This is a guy, who implemented rap notes in USDX in the beginning of 2017.
https://github.com/UltraStar-Deluxe/USDX/pull/210
This is "his" pull, which was then merged into the build.
Maybe this helps you, understanding what is happening there.

I created a small video to show, what I mean. It's on my GDrive, here is the link:
https://drive.google.com/file/d/1ZpOmNFvigUOAsS0oykChQN__zuy3Ds2K/view?usp=sharing

**Comment by Stefan1200-de** [comment]
Thanks for that video. Was it because of the video recording, that Vocaluxe was lagging so bad?

In the first step I add reading R and G notes as Freestyle notes. That allows loading that songs in Vocaluxe (can be useful for songs, which only have some lines of rap notes, while the most lines are normal notes).

For the real implementation much more work has to be done. The code base and coding language between Vocaluxe and UltraStar Deluxe is too different to be able to use it somehow.

**Comment by JanK118** [comment]
Yes, recorded this on my notebook, the screen recording caused the lags and audio stuttering. 
I understand, that the code base is very different, and the links were not meant to be directly “used”, I thought it could help somebody to get behind what was done in USDX. I don’t have any programming skills, but from my perspective, I thought “reverse engineering” what they have done, then “translating” it to the Vocaluxe programming language would be a viable option. 
(To be honest, I installed Visual Studio and cloned the repo, but man, that is a whole new universe for me, I didn’t even know where to start to look at) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Stefan1200-de** [comment]
Well, in fact it is not so difficult. Like you said, USDX just ignore the tone pitch on RAP notes, points for rap notes are the same, as for normal notes. All other changes they made are just visual stuff, because RAP notes are displayed different on the sing screen, displayed that icon on the song screen and loading that txt files with RAP notes.

**Comment by JanK118** [comment]
> [...] displayed that icon on the song screen [...]

I had an idea for that icon, guess what inspired me... 

![Screenshot](https://user-images.githubusercontent.com/60331177/73798676-df579b00-47b3-11ea-9091-54e6dd20f668.png)


(I'm not a professional designer so it's crappy if you zoom in closer in the original file, but on screen it works I think)

**Comment by Stefan1200-de** [comment]
Yeah, looks nice. :)

**Comment by JanK118** [comment]
I just saw „by accident“, that @GaryCXJk is active in the Vocaluxe community (see #416 if I remember correctly). 
I think he could help us here... ;-)

**Comment by GaryCXJk** [comment]
Coincidentally I actually am working on it (and have been using it for karaoke at work), but it doesn't look great at the moment. I'll see if I can improve on it, but it might take time, since I have other things as well.

**Comment by Stefan1200-de** [comment]
@GaryCXJk wonderful, take the time you need. So I can use my time for other stuff around Vocaluxe. And to be honest, I don't need rap notes support for my own personal use, so I'm very happy with it, if I can get help here. The current nightly of Vocaluxe just loads rap notes as freestyle notes (added / changed 3 lines at the CSongLoader for it).

**Comment by GaryCXJk** [comment]
Okay, so, it's been over a month, so I feel like I should report back.

In this time, I haven't really been able to work on it. I mean, technically it already works, and it works pretty consistently. I've only tried it with one song (Pee Pee Dance from Teen Titans GO!), and it works consistently.

The main problem is that graphically, it looks like crap. I could take a screenshot or a video, and I might do it at a later time, but basically, at the moment, it's a regular note stretched out from top to almost bottom. I say almost bottom, because once the rap note is hit, you can see the highlight of said note under the big note. It's something that I either need to fix, or rewrite so that it works similar to how I implemented it in Ultrastar Deluxe.

I have the rap branch on the fork I'm working in, I do need to figure out where the code was, since it's been quite a long time since I last worked on it.

**Comment by Stefan1200-de** [comment]
Don't worry, take your time. I'm happy that you support this project. Thanks for this update.

**Comment by daggeg** [comment]
It's just appreciated you looking into this so take your time. One thing I came to think about though, is it a problem that Vocaluxe has got a more detailed point system compared to Ultrastar Deluxe? I mean if you're trying to reverse code your own code from Ultrastar Deluxe?

**Comment by daggeg** [comment]
> Well, in fact it is not so difficult. Like you said, USDX just ignore the tone pitch on RAP notes, points for rap notes are the same, as for normal notes. All other changes they made are just visual stuff, because RAP notes are displayed different on the sing screen, displayed that icon on the song screen and loading that txt files with RAP notes.

I just realized that this way of implementing rap notes is not ideal. Because if used this way the worst rapper can come out on top every single time. By just keeping a monotone humming going you will score 10,000 points each time. 

I don't know how this would be done nor how Sony solved this problem. But the best way would have to be a scoring algorithm that would give points for timing alone. Because that's what rapping is about, skills and flow. So I reckon that points were to be given if you timed the word/syllable at the "exact" time (+/- some milliseconds). Perhaps it would be possible to detect the timing as an increase of volume relative to the moment before? 

Regarding Sony's solution, I see that you @GaryCXJk wrote the following about your solution implemented in USDX: "Essentially rap notes are counted as regular notes, except the pitch doesn't matter. This is similar to how later iterations of SingStar implemented rap notes."

It would be really cool to know how Sony implemeted rap notes. And did they use another solution in earlier iterations?

**Comment by daggeg** [comment]
Do you guys think it would be a viable option to let the rap scores be based on an increase of at least 10% (or any other feasible increment) of the volume at the exact time of the position of the syllable/word compared to the volume registered 5ms (or 10ms or...?) prior to that exact timing position? 

Would this be possible to code or would it be too difficult, alternatively lead to unwanted problems?

**Comment by daggeg** [comment]
Perhaps the easiest way is to implement it like proposed and then set the all the rap notes at minimum length? This way timing becomes essential as long as you’re trying to rap and not just mumble.

**Comment by GaryCXJk** [comment]
Sorry for being gone for so long, I hit a snag I was only able to fix today (due to having some time).

![afbeelding](https://user-images.githubusercontent.com/646757/122060470-eb169100-cded-11eb-99bc-8e866c8d1451.png)

Right now this is what the song screen looks like. Right now the icon placement is between medley and duet, though of course it can be altered. This is what tripped me up, because I wasn't entirely sure if it was mandatory to change the theme files.

![afbeelding](https://user-images.githubusercontent.com/646757/122060522-f8338000-cded-11eb-9e5a-d7059a3ad17b.png)

Right now the rap notes look like this, which... isn't great. For now it works as a great placeholder, though.

My opinion on how to handle rap notes? Let the user decide. I haven't implemented it yet, but my idea is to have an option in the settings, which you can set to "Freestyle" (just how it is at the moment), "Full Note" (how it is the way I implemented it), and "Minimum Length" (what @daggeg proposed).

About the proposal of trying to detect how long a note persists on the user's side, while it does sound like a good idea, even with official products like SingStar and Let's Sing, there's quite a bit of artifacting going on, due to background noise or other factors that would be more frustrating for the player than it would be for a programmer to implement. If such an implementation were to be added, I would probably lock it behind the higher difficulties, or at least make it configurable in the settings.

EDIT: Replaced the screenshots.

**Comment by Stefan1200-de** [comment]
@GaryCXJk well, I just implemented a simple fix of reading rap notes as freestyle note, because without that quick fix Vocaluxe was just crashing. And with this quick fix you are now able to open and play this song in general.

It was not my intention to implement this Freestyle thing as the new standard. My quick fix was just better than a crashing Vocaluxe. ;)
If you have a better implementation for rap notes, feel free to add a Pull Request, so we are able to look into it and merge it, if it works good.

**Comment by Stefan1200-de** [comment]
Here is my simple and quick implementation:
https://github.com/Vocaluxe/Vocaluxe/blob/57fdf691706b0b26c04abed0f7f6fe5b86fddd1c/VocaluxeLib/Songs/CSongLoader.cs#L574-L575

**Comment by GaryCXJk** [comment]
I've done a tiny bit of research, and apparently, in SingStar, the rap notes use a combination of [speech recognition technology and rhythm detection](https://web.archive.org/web/20070408075151/http://ps2.gamezone.com/news/04_03_07_09_27AM.htm).

I doubt it's worth the time to actually do speech recognition, which leaves us with rhythm detection.

Now there's another option we could explore, and that is to see how Let's Sing handles rap notes, though, truth be told, I don't have a lot of confidence in that option. From what I remember when I last played it (and there was only one song that actually had "working" rap notes from the songs I did, Pump Up the Jam by Technotronic), it was basically just a short note where pitch wasn't important. Now I'm not sure if just making a continuous noise would work or that you actually had to make effort to at least do the correct rhythm, if anybody has the game (I played the PS4 version, and the friend who had the game had only purchased one song pack if I recall correctly), maybe it could be worth (?) checking it out.

For the moment, I have a working branch with rap notes. I'm in the process of adding graphics for the rap note (for now it just uses the regular notes graphics, someone else would need to create proper graphics for rap notes), but at least it works.

**Comment by daggeg** [comment]
I’ve never played Let’s Sing so I can’t help out with that. But I also think that rhythm detection is the only feasible route to take.

**Comment by marwin89** [comment]
@GaryCXJk 
-  #578 is now merged into develope branch.
- It will be released in v.0.5.0 (~ spring 2024)
- Thanks for your work! top👌 At least we have a basis now (with getting points) 🎉🙂
- (@stefan1200-de thanks for the "Free-Style-Workaround)
---
To go the next steps:

From a UI Designer perspective:
- @GaryCXJk could you do a pull req, making the notes smaller, like just 50% of what it is now? 
- Always vertical middle aligned (for each player)?
- with different note shapes like:

![Image](https://github.com/Vocaluxe/Vocaluxe/assets/63517874/daecdecf-2960-4db2-b2ec-d0bf037b8388)

then it's quite visible that these are pitchfree rap notes

From a Game Designer perspective:
- just one rule to handle rap notes. more only confuses players in the end (+ blows up complexity of code)
- I vote for "minimum length"

**Comment by marwin89** [comment]
## Voting / Handling of Rap notes 📈 

Dear all,

please vote here with emoticon reaction for the handling of rap notes:

minimum length = 🚀 , full length notes = 🎉

voting ends on Jan 31th 2024

**Comment by GaryCXJk** [comment]
I might see what I can do, but personal circumstances as well as other reasons might prevent me from working on non-work related programming. I did try to change it before, but I only got it to crash.

**Comment by marwin89** [comment]
@GaryCXJk : That's okay, take your time. I'll try to engage more programmers, artists and game designers the next months.

If someone else would like to round up the rap note feature, let us know. this would boost our v0.5.0 release. 🙂

**Comment by marwin89** [comment]
### Testing
- Could someone send me a proper rap song txt-file for testing? 👋 
- I tested rap notes (in nightly build from 10 Jan 2024) and I'm not sure if I do something wrong with txt-file.
- In this case rap notes are not displayed and there are no spaces between the lyrics
- Song: [Peter Fox - Schwarz zu blau.txt](https://github.com/Vocaluxe/Vocaluxe/files/13937467/Peter.Fox.-.Schwarz.zu.blau.txt)

![Image](https://github.com/Vocaluxe/Vocaluxe/assets/63517874/5f32f5fc-e711-47a1-8b9f-0d649b7e38d2)

**Comment by marwin89** [comment]
@GaryCXJk / @daggeg FYI : I added rap note textures in this PR #671

**Comment by jecrs** [comment]
Hey! this issue is almost 4 and rap notes still break vocaluxe...

**Comment by marwin89** [comment]
### Testing

I tested the rap notes feature successfully after merge of #708 . We now got basic rap note support:
- scoring without pitch, only timing is relevant ✅ 
- rap notes have own texture ✅ 

It's better than before, but rap notes need finetuning: 
- all rap notes need to have same position, since pitch doesn't count ❌ 
- lyrics miss white spaces ❌ 
- advanced rhythm detection (rap-o-meter) would be cool ❌ 

I open up a seperate issue:
- #718 

Thanks to @Rap-Voca and all the other contributors.

![rap-notes-basic-support](https://github.com/user-attachments/assets/d0ded31b-62b4-4e4d-bee3-616760d8d263)
