### ISSUE TITLE
unc path for song folder

### ISSUE THREAD

**Issue by god-Mike** [Vocaluxe/Vocaluxe#537]
Hi,

all my songs are stored on my NAS, so i changed the SongFolder to `\\mynas\share\_vocaluxe\songs`. 
On startup all songs are loaded and they are displayed in the list (with covers) but if you click on a song there is no autoplay and even when you try to sing a song, no song/video is displayed and you immediately come to the result page. 
I mapped the network share in windows 10 pro, to get a drive letter for it `Z:\_vocaluxe\songs` and used this as SongFolder. 
This just worked and you are able to sing a song (autoplay also working).

So there seams to be an issue with unc paths that should be fixed.

**Comment by Stefan1200-de** [comment]
I can confirm this, having the same problem with the current nightly. Cover images and song names are loaded successfully, only audio and video files can't be loaded using UNC path.

Without checking the code, I try to guess, why Vocaluxe has this problem.
We use an external library to load video and audio files, while cover/background images and txt files will be loaded internal. While Vocaluxe (written in C#) itself supports UNC paths, I guess the external library written in the C languages does not.

I see this as a very low priority issue, because maintaining external librarys are a little bit more complicated and this issue has a workaround (creating a drive letter, just use the same drive letter on all systems).

@lukeIam Can you confirm my guess? Is this easy to fix on your end, or do you confirm, that this is much more complicated as it sounds?

**Comment by lukeIam** [comment]
> @lukeIam Can you confirm my guess? Is this easy to fix on your end, or do you confirm, that this is much more complicated as it sounds?

@Stefan1200-de Yes, I also think that's a problem of the ffmpeg library. I've did a short search but haven't found a workaround that we could apply to Vocaluxe.
Assigning the the network path a drive letter as @god-Mike described seems to be the only solution so far...

**Comment by marwin89** [comment]
I close this issue due inactivity and low interest. please re-open if needed.
