### ISSUE TITLE
Mouse pointer jumping in to the middle of screen over and over when playing nightly. 

### ISSUE THREAD

**Issue by askusbloodfist** [Vocaluxe/Vocaluxe#551]
Ive tried using opengl and direct3d to see if it would stop akting this way. 
ITs a new installation running on intel pu and nvidia gpu 2070.

**Comment by askusbloodfist** [comment]
Seems to be the applikation DS4Windows in combination with yours that does it.

**Comment by Stefan1200-de** [comment]
In my opinion in this case the developer of DS4Windows should fix this "bug".

**Comment by Stefan1200-de** [comment]
Did a quick look into this one. In Vocaluxe with a right thumb stick the mouse movement will be simulated. With a real XBox 360 controller this is working great and nothing happens, if you don't touch the right thumb stick. I can only guess that DS4Windows or your PS4 controller is sending any movement of the right thumb stick to Vocaluxe. Because if the right thumb stick is centered, the mouse cursor will it also.

**Comment by askusbloodfist** [comment]
Yeah seems to be correct about the ds4 closing the ticket.
