### ISSUE TITLE
Feature request: Render in higher resolutions

### ISSUE THREAD

**Issue by Edi316** [Vocaluxe/Vocaluxe#552]
Currently Vocaluxe renders everything in the resolution 1280x720, regardless of the screen resolution. So my feature request is, that Vocaluxe is able to render in higher resolutions (at least in HD - 1920x1080).

I don't how time consuming this task is, but maybe someone, with programming skills, is able to look into that option.

Thank you in advance!

**Comment by brunzel** [comment]
1280x720 is only the internal positioning resolution, the game renders to the current screen resolution.

**Comment by Edi316** [comment]
From my experience it is always 720p upscaled to the screen resolution. For example: A 1080p video gets downscaled to 720p and then upscaled to the higher screen resolution instead of playing in native 1080p.

**Comment by daggeg** [comment]
That’s how I have understood it too. Hence the lag when using videos at a reslution of 1080p, which is quite annoying to be frank.

**Comment by Stefan1200-de** [comment]
Okay, related to the information from brunzel, my text is wrong.

Old post:
Yeah, that is true. Everything is rendered in 720p and up-scaled to the current Windows resolution. This kind of changes are something which I don't want to do, because of my just basic knowledge of the C# programming language. But in general I support this idea.

**Comment by brunzel** [comment]
No, it is not rendered in 720p. The internal resolution of 1280x720 is just for the positioning grid. It has nothing to do with the actual rendering. The rendering resolution is depending on the actual screen resolution.
@daggeg: The lag of the video decoding is because it is done by software. There is no hardware accel. in the current code for video decoding.

**Comment by brunzel** [comment]
@Edi316 : you can improve the visual quality. Delete the "CoverDB.sqlite" and change in the "Config.xml" the param for "TextureQuality" to "TR_CONFIG_TEXTURE_HIGHEST" and "CoverSize" to 512. This will increase the texture quality and font quality.

**Comment by daggeg** [comment]
@brunzel, would it be possible to implement a solution for hardware acceleration in order to solve this "problem"? I started replacing all 1080p videos with 720p ditos about a year ago due to the, at times severe, lagging. But I wouldn't mind replacing them again :)

**Comment by Stefan1200-de** [comment]
@lukeIam I know we updated ffmpeg about a year ago. Is there a possibility to enable hw accl?

**Comment by brunzel** [comment]
i am using hw accel video decoding on another c# based program. but this program is using FFmpeg.AutoGen. the keywords are "av_hwdevice_find_type_by_name", "avcodec_get_hw_config", "av_hwdevice_ctx_create" and "av_hwframe_transfer_data". but the last one is not the fastest one, because the cpu still must convert the frame format and upload it into a gpu texture. this is not optimal. i have found another way, where the gpu does the fomat conversion by using cuda and leaves the frame data on the gpu - but this is nvidia only. but there it works great, it is possible to decode up to 2 uhd streams or 8 fhd streams at the same time with 30 fps.

**Comment by lukeIam** [comment]
> @lukeIam I know we updated ffmpeg about a year ago. Is there a possibility to enable hw accl?

as @brunzel already mentioned it's not that easy as enabling a flag.
Most of the hwaccl decoders do not return a frame but just a pointer to the surface containing the rendered result (zero copy of the frame - it will not copied into ram/cpu).
I played around with DXVA(2) that should work with all windows systems but was not successful integrating it into the architecture of Vocaluxe.

I also played around with the same rendering as the current but using an different color encoding - saves about 50% of the size that needs to be transferred (see https://github.com/Vocaluxe/Vocaluxe/issues/198).
But I never got it fully running/stable.

My best idea to get video accl and also combability for other systems was rewriting the UIs in Unity.
I was playing around with their alpha yoga based new ui engine (is now stable: https://docs.unity3d.com/Manual/UIE-LayoutEngine.html).

But had/have so many other things to do that I've never followed this path futher...

**Comment by daggeg** [comment]
A stupid question perhaps, but I haven’t used any other Ultrastar software for donkey years..., can the other softwares render  videos in e.g. 1080p without lagging? If so, what have they done differently?

**Comment by lukeIam** [comment]
> A stupid question perhaps, but I haven’t used any other Ultrastar software for donkey years..., can the other softwares render videos in e.g. 1080p without lagging? If so, what have they done differently?

maybe https://github.com/UltraStar-Deluxe/Play can - I haven't tested it but it uses Unity 2D and if it also uses Unity's video player they get hwacellerated video playback for free.
