### ISSUE TITLE
Improve gamepad controls

### ISSUE THREAD

**Issue by steump** [Vocaluxe/Vocaluxe#553]
Hello, first I like to say thank you for the awesome work!

In the nightly-version I cant select the jokers with a controller.
For example in the challange-mode (the Tik-Tac-Toe didnt work anyway)

**Comment by Stefan1200-de** [comment]
Just checked that code. The implementation for the Gamepad is quite simple. Currently in **CGamePad.cs** -> **_HandleButtons()** only the following keys are matched with a keyboard key:
**Digital Pad** (DPad) with the **Arrow** keys
**Start** button with the **Space** key
**Back** button with the **Back** key
**A** button with the **Enter** key
**B** button with the **Escape** key
**Trigger Left** with the **Page Up** key
**Trigger Right** with the **Page Down** key
**Shoulder Left** with the **Left Mouse Button**
**Shoulder Right** with the **Right Mouse Button**

In addition to it, you are able to move your mouse pointer with the **right thumb stick**. This is currently the only way to select a Joker with the GamePad. So if you use the **Shoulder Left** button to simulate the left mouse button, while you are moving the mouse cursor with the **right thumb stick**, it is quite easy to select the joker. At least with an XBox 360 controller.

Implementing a direct way to select Jokers with the GamePad is not done fast, because it needs to be a way to select the team first. So I can't simple match a GamePad button to a key on the keyboard (which is currently key 1 to 6). But can you test, if using the **right thumb stick** and **Shoulder Left** is already helping you?

**Comment by Stefan1200-de** [comment]
Updated my text above, because I found the GamePad keys for the left and right mouse buttons.

**Comment by steump** [comment]
Just tested and yes I can select the Jokers with the right thumb stick an the LB button on my XBOX Wireless Controller (it's a littlebit tricky, but works for now - thanks for the tip). In the Tic-Tac-Toe mode the selection works fine, because there is a dircet way to select, it would be great if the function implementing in the Challange mode too. Also important: The Player selection ist very difficult with the controller, this is not working with the workflow above - you need the mouse.

**Comment by diegopau** [comment]
An improvement I would love to see is that right now when you use the gamepad to move through the list of songs or tabs you can't continously move up or down (or left or right) through the list by holding the related gamepad button as it would be expected. For instance, if you are moving down through the list, you are either using the d-pad down button or the RT button (in a Xbox 360 gamepad), and you have to hit it each time you want to move a step further instead of just holding it down and move smoothly through the list.
