### ISSUE TITLE
TicTacToe Mode microphone and team menu unclear

### ISSUE THREAD

**Issue by henningblubb** [Vocaluxe/Vocaluxe#561]
In the tic-tac-toe mode is not clear visible which microphone is used by which team and also the labels are unclear

**Comment by Stefan1200-de** [comment]
We tested yesterday the TicTacToe mode together, first time for us. The following things was weird for us:
1. Position of the labels for "Team 1" and "Team 2" exactly above the two selected players can be mistaken as team and not player selection.
2. I needed very long to understand, that I can remove a selected player by clicking with the right mouse button on it.
3. It was not fully clear who has to sing with which mic, because I had 4 mics connected (player 1 to 4). In TicTacToe mode it was not possible to see, which is active (unlike the normal player selection screen outside of party modes).

My ideas:
For 1.: Changing the player selection screen a little bit, to make it more clear, that the team labels has nothing to do with the selected players below, to make it easier for players first time using TicTacToe party mode.
For 2.: Implementing a help text line at the bottom like on the song list screen (something like "Add at least one player to both teams! / Drag player avatars to add them! / Right click player avatars to remove them!"), to make it easier for players first time using TicTacToe party mode.
For 3.: Adding the equalizer from the normal player selection screen (screen names) also to the TicTacToe main screen below the player names, to make it possible to find the right mic before start singing.

As soon as I have some spare time for coding, I will look into it.

**Comment by Stefan1200-de** [comment]
I implemented my ideas in my own branch, check out my screenshots. Any suggestions?

Player selection screen, I added a help line at the bottom and added a text label below the team selector:
![image](https://user-images.githubusercontent.com/15168351/137810260-93ea3946-f94b-4e8e-a29b-2b36bcff6177.png)

Tic Tac Toe main screen, changed the player name area, including a mic equalizer below the player name:
![image](https://user-images.githubusercontent.com/15168351/137810307-675aebb3-5bc4-4cc9-8b1d-08f79399a87a.png)
