### ISSUE TITLE
Performance optimizations & project walkthrough

### ISSUE THREAD

**Issue by flennic** [Vocaluxe/Vocaluxe#584]
Hey yo peeps,

first of all, thanks for the project, we use it quite extensively in our friends group and we enjoy it quite a lot.

We face mainly two issues:

- We have a rather large library which needs quite some time to load (9000+ songs).
- Sometime in the middle of a session, the program crashes and then we have to reload while everyone is waiting.

Hence I had the idea to try to log the errors / crashes and also try to optimize the program in how it handles the amount of data, but first I have to understand how it works and behaves (for the behavior I can ask friends who use the project quite a lot).

The project is based on .NET framework and mono which is a bit outdated but okay, but the C++ project 'Pitch Tracker' is impossible to compile on macOs/Linux and even on Windows an old Visual Studio version which supports the Platform Toolset v100 is required.

From the looks, the C++ project does not look too large or complex, so maybe there is a way to rewrite it in C# as well. Or does it have some specialties? As I didn't have time yet to inspect the project in detail (and couldn't compile it yet due to the lack of an older VS version) I have basically two questions:

1. Your estimation, how hard will it be to replace the C++ project and is that even a "possible" thing, something to keep in mind?
2. What is your estimation for migrating the project to a .NET (Core) version, even a thing to do with not too much effort as it depends on Windows Forms. Linux seems untested, but do Windows Forms work on Linux/macOs or is MAUI or Avalonia)?

I do not have so much experience in desktop development, but quite extensively in web development. So an additional question would be, if anyone of you has some time, would there be the possibility for a walk-through through the project?

Would be nice to hear back from you and again thanks for the work you have done so far :)

Regards,
Maximilian

Edit: Found the Linux guide, but the basic idea still holds that the development experience on macOS/Linux is not nice (crashing issue) and VS2013 is nowadays only available via a Visual Studio Subscription

**Comment by lukeIam** [comment]
Hi Maximilian,

> but the C++ project 'Pitch Tracker' is impossible to compile on macOs/Linux and even on Windows an old Visual Studio version which supports the Platform Toolset v100 is required.

I don't really see the problem here: "Pitch Tracker" is a unmanaged c++ component which also brings us speed and it build under Linux without problems.
But Vocaluxe for Linux was more a theoretical proof of concept: more info here https://github.com/Vocaluxe/Vocaluxe/issues/161
Regarding the Platform Toolset: you can also use newer toolsets without any problem.
There is even an auto selection build in (so that it does not have to be build manually): https://github.com/Vocaluxe/Vocaluxe/commit/dad48b9686e6a11e8be3372f1e22ba551f136a6e
-> so you can build also with newer VS versions

Upgrading the .net version wouldn't be too hard I think - but I also think we are not really winning something from it.

But I agree with you that a rewrite of some Vocaluxe components would help a lot with performance and combability for other os.
The main problem I see here is the UI - we are using the most resources to decode and render the video. 
And with the current Windows Forms UI approach im my opinion it we never achieve GPU accel decoding with zero-copy rendering. 
In my opinion the best way to go would be to separate UI and logic + reimplement the UI in e.g. Unity.
There we could use the out of the box video playback component where we get all the magic for free.
-> Vocaluxe would most likely run on low power devices like raspberry pi (even android is thinkable)
Also it would make sense to make the ui dynamic sizing so that it rendered in display resolution and fit to all.
Unity has the UI Toolkit which is more or less flexbox for Unity ;)

A long time ago I already startet splitting UI and Logic and doing prototypes in unity - but I never got farer than the starting point (https://github.com/lukeIam/Vocaluxe/tree/ui_study_yoga).

But the overall problem here is that Vocaluxe has no longer real developer capacity.
@Stefan1200-de does his best to keep it alive (thanks!) but I don't think he has the capacity to rewrite big parts of Vocaluxe.

**Comment by flennic** [comment]
Hi lukeIam,

Thank you for all of the great information and explanation. I like the concepts which you mentioned about Unity and separating the logic and UI. Nevertheless, I also see the issue with developer capacity, which is usually the most limiting factor. So for now I suppose that the best is to not start something major there.

For my part, I will try to get the project compiled and running on Windows with your provided help with the auto selection build within the next weeks (I do not have so much free time the next two weeks, so it might take a moment). Also, at the moment, I do not have access to a Windows machine so I have to fix this first. I will then look into my mentioned issues (crashes + long loading times) and will see if I can do something about it. If yes, then I will create a PR or will ask more detailed questions along the way.

Again, thanks and maybe I will learn a bit more about the project when working with it.

Regards,
Maximilian

**Comment by Stefan1200-de** [comment]
> But the overall problem here is that Vocaluxe has no longer real developer capacity. @Stefan1200-de does his best to keep it alive (thanks!) but I don't think he has the capacity to rewrite big parts of Vocaluxe.

Not only the time: I currently don't have the coding skills to change major stuff or play around with Unity & C++ librarys.
Thats why I only do smaller stuff, if I find some time for coding.

**Comment by marwin89** [comment]
Hi @flennic , @lukeIam , 

did you know there is a young ultrastar fork called ["Ultrastar Play](https://ultrastar-play.com/de)", that is build on unity? It turned out to a commercial fork called [Melody Mania](https://melodymania.org/en) this year's summer. A Developer is putting much effort in it. Maybe it can handle 9000+ Songs? Give it a try.

If you like to take part , look in our new disussion section on GitHub, opened this week. I try to boost Vocaluxe with a new additional design and avatar pack in #602 

Regards

**Comment by lukeIam** [comment]
Ultrastar Play is also quite old but it made nice progress in the recent time 👍 
(basically they have gone the unity way we planed and never gone)

**Comment by jimmyhawkin** [comment]
I Wish i had the skills needed to help you guys out to turen Vocalux over to unity. Vocalux is a better Software the. Current all versions of Ultrastar cause of its good video compability and general handeling of Songs. Ultrastar is just a crasy mess. I just Wish i could code so i could keep vocalux going forward. My Whitley Family use it weekly. But as formats are Loving to 4k the Software rendering is becomming trubbel some.

**Comment by marwin89** [comment]
@lukeIam , @Stefan1200-de 
Are there certain reasons why there is a lack of dev power for vocaluxe?  Is it too hard to motivate new devs? Or is everybody waiting for ultrastar play right now?

I always wondered how I can donate to the team or individual devs. But maybe you already discussed that?

As a user I would love to have an overview - just a list like

- "Dev XYZ": Jukebox, Song Screen Improvements -> Donate to DEV XYZ link…
- "Dev XYZ": Linux Support, browserApp -> Donate to DEV XYZ link…
- "Dev XYZ": Unity Migration - > …
- "Maintainer XYZ": Documentation, Website, News, Discussion -> Donate….
- "Designer XYZ": Animation, … -> Donate link

**Comment by lukeIam** [comment]
> Are there certain reasons why there is a lack of dev power for vocaluxe? 

I can only speak for myself:
I'm not longer a student and having a full time job now.
Also to be honest having other (smaller) projects...

Maybe I would develop another feature or something but maintain and modernize the whole project is way to big.

Edit: For me this was never about receiving donations - I did it because I wanted to make Vocaluxe better for everybody (for free).

**Comment by Stefan1200-de** [comment]
Well, I also have a full time job and of course more hobbies than coding.
Not to forget that my C# knowledge is quite limited. Vocaluxe was my first try coding in C#.
But I was coding in the Java language for many years, so I was able to do smaller stuff quite fast after looking into the Vocaluxe code.

To be honest, the main reason to start coding with Vocaluxe around 4 years ago: I missed some smaller features in Vocaluxe and was annoyed of some bugs. So I started my own fork to change something. It doesn't took long until I was contacted by @lukeIam and @flokuep, thanks for that :)

But of course, I also fixed some issues reported by the community. But my knowledge is still very limited if we talk about bigger complete new features, changes related to C/C++ libraries (like ffmpeg) and hardware acceleration. And I don't have the time to go much deeper into this.

But as soon I see something, which I'm able to do, I would be happy to change something, even if it's just smaller stuff.

**Comment by flennic** [comment]
@marwin89 Thanks for the mentioning and the update. To keep it short, at the moment I do not have time (or priority) to get involved with Vocaluxe or any other projects in this area. But I really appreciate you reviving this discussion and your work!

From my side, this issue is considered as done (because I asked for the walk-through). I will leave it open for you to continue with the discussion but I am more than fine with you closing the issue if you feel like it.

Kind regards,
flennic
