### ISSUE TITLE
#TAGS-Attribute causes duplicate songs when Tab=Off

### ISSUE THREAD

**Issue by marwin89** [Vocaluxe/Vocaluxe#670]
### Vocaluxe Version:

Latest nightly build (2024-01-10)
OS: Windows 10
Vocaluxe running in language: English

### What is the problem?

#TAGS-Attribute shows duplicates of the same song for each entry in TAGS,  when Tab=Off 
![Vocaluxe-QA-Tagsfeature-01](https://github.com/Vocaluxe/Vocaluxe/assets/63517874/4566d4b4-136c-48c7-8dca-e7999d5cc126)

### Steps to reproduce

1. Give a song multiple entries comma seperated in #TAGS-Attribute like: #TAGS:Party,Feel-Good
2. Start Vocaluxe and set Tabs = off
3. Go to song screen
4. Look for the song with multiple entries
5. For each entry in TAGS-Attribute the same song is listed multliple times

### Additional context
We recently introduced TAGS-Feature
- #624
- #630  

### Log(s) & preferences file(s)
-

**Comment by flokuep** [comment]
Do we have the same behaviour if we have multiple editions tag within a song file?

**Comment by marwin89** [comment]
FYI: @flokuep 👋🏻🙂

**Comment by flokuep** [comment]
Guess it's intended within the code https://github.com/Vocaluxe/Vocaluxe/blob/develop/Vocaluxe%2FBase%2FCSongSorter.cs#L182

The idea behind it is that the song should appear at every tag (or genre or edition) within the sorting. That makes sense for larger collections: if you scroll through your list and see some rock songs you expect to see also a song that is classified as rock and indie. I agree that it is a bit strange in smaller collections... But might be the easiest way to go. Otherwise we need to decide which value should be used for sorting.

**Comment by marwin89** [comment]
Edition tag looks fine
(but I guess it's because there are no multiple entries for editon see screenshot
![Vocaluxe-QA-Tagsfeature-02](https://github.com/Vocaluxe/Vocaluxe/assets/63517874/34c2f173-bbae-4060-8960-6c7d853e14f5)
)

**Comment by marwin89** [comment]
Ahh, okay, that sounds reasonable.

**Comment by marwin89** [comment]
I close this 👍🏻
