### ISSUE TITLE
New theme Ruins the Jukebox experiance. Please remove logo when Background video is enabled. 

### ISSUE THREAD

**Issue by askusbloodfist** [Vocaluxe/Vocaluxe#678]
Best thing about jukebox experiance is that you can leave the musik on and get people thats at the party to feel the grove and get them singing. All my guest agreed that it was a bad idee to have the Logo covering the Bakground video to the point that it was anoing. The new Vovalux big logo covers the middle and that was never the case with the old versions. I know i started Vocalux i dont need to see that when using background video all over the screen ruining the party and the Jukebox experiance. 

Please remove the logo from the jukebox screen. When background video is enabled and own musik is selected as a combination this should remove the Vocalux logo. Mainly when you select bakground video in menus. I understand that this must been a mistake. Just please korrekt it :) 

And please do this as quikly as possible. Thx. Other then that love the theme But the V in Vocalux should be big and not smal. And i think a Microphone should be in the logo insted of Waves in the o. Or keep the Waves but put in a microphone lik the old logo had. Allso. when Vocalux is loading. Make the logo Transparent. Like it was in the old one.

**Comment by jimmyhawkin** [comment]
Can only Agree with the post. I allso just tried the new theme. And the logo should not exist when Using background video in my opinion. Its just ruins the experiance.

**Comment by jimmyhawkin** [comment]
Any fix for this on its way?

**Comment by flokuep** [comment]
@marwin89 can you have a look on it? Jukebox mode is activating the background video of the background music (which is set to songs instead of the background music file)

**Comment by askusbloodfist** [comment]
I would be thankful if this could be done before friday as i dont have an old version left to switch for. And on friday i am going to use it at a party :)

**Comment by marwin89** [comment]
hmm yes, the logo XML-Element should fade while videoplay back is active. But this is a task that has to be done by coders - I'm UI designer not a coder. It's hard to motivate any game devs for this project since vocaluxe is a custom game engine and unpaid.

@flokuep: could you add some code to fade the logo-element? do you have time? 

Actually this problem will be solved automatically in future: the MainScreen will be re-arragend in future anyway (with big sliders and more functionality) and will not be a jukebox screen anymore. For a Jukebox mode with videoplayback there will be a new separate subscreen without any logo where you can actively browse songs like in song screen. This is a task that has to be done by coders for some years now:
- #452 

@askusbloodfist as a quick workaround: just make the image-file transparent via paint or other graphic tools.

**Comment by flokuep** [comment]
Mhm. Fading seems to be a really hacky workaround. The more robust solution: add a new empty (jukebox) screen without any functionality except switching back to main. Screen can be entered via pressing "J" on the main screen. The real implementation would need to be done in the referenced issue.

Would that fit your needs?

**Comment by jimmyhawkin** [comment]
To be honest what is rude about this post? Both Askus and myself are asking for a change that has ruined a funktion that people are using in the Software for years. that 1 looks bad. 2 ruins a funktion that once existed and people are using. No one has been rude other then calling out a bad thing in the software that people has Been using for Years. That you can’t handle that is ovius. But if anyone is rude then it’s you. Pushy maby. But asking if it can be fixed quickly is that rude? Come on man. It’s an open software with an open community using it. Maby changes like this
Should be better discussed before you go and do that sins it oviusly ruined the experience for people. Can we leave rudeness out of this and many fix the problem instead untill you are ready to do what you wanted to do later. No one is trying to be rude. I think it’s a language barrier. And again a release of a function that was not thought of all the way as askus said. But when we break thing. Maby we should fix them instead of calling out people for being rude when they ask for a change.

**Comment by jimmyhawkin** [comment]
> Mhm. Fading seems to be a really hacky workaround. The more robust solution: add a new empty (jukebox) screen without any functionality except switching back to main. Screen can be entered via pressing "J" on the main screen. The real implementation would need to be done in the referenced issue.
> 
> Would that fit your needs?

In my opinion the function to enable background video was always to have it so when you start the software random Musik runs in the background and people have an easy way to fast get started on singing. And people could watch the movies of songs they heard but never seen the video. If that could be a separated menu choice instead to go in to jukebox mode then that works just
The same. Cause then maby one can have the menu item gone while playing aswell?

**Comment by marwin89** [comment]
Issue is closed. Please use the quick workaround mentioned earlier. Problem will be fixed with following issue:

-   https://github.com/Vocaluxe/Vocaluxe/issues/452
